#!/usr/bin/env python
import argparse
import os
import subprocess


abspath = lambda f: os.path.join(os.path.dirname(__file__), f)


def gen_tapset_macros(binary, tapset_dir):
    with open(os.path.join(tapset_dir, 'py_library.stpm'), 'w') as f:
        f.write('@define PYTHON_LIBRARY %( "{}" %)'.format(binary))


def main():
    argparser = argparse.ArgumentParser()
    argparser.add_argument('-x', '--pid', help='PID to profile')
    argparser.add_argument('-t', '--time', default='30',
                           help='Time to run profiler, in seconds')
    argparser.add_argument('-d', action='append', dest='extra_loads',
                           help='Load symbols from these additional modules')
    argparser.add_argument('--py3', action='store_true',
                           help='Pass when profiling Python 3 programs')
    args = argparser.parse_args()
    assert int(args.pid) > 1

    binary_path = os.path.realpath('/proc/{}/exe'.format(args.pid))

    #stapscript = './py3sample.stp' if args.py3 else './pysample.stp'

    stapscript = abspath('sample.stp')
    if args.py3:
        tapset_dir = abspath('../tapset/python3')
    else:
        tapset_dir = abspath('../tapset/python2')

    gen_tapset_macros(binary_path, tapset_dir)

    stap_cmd = ['stap', stapscript, args.time, '-d',
                binary_path, '-x', args.pid, '-I', tapset_dir]

    if args.extra_loads is not None:
        for l in args.extra_loads:
            stap_cmd.extend(('-d', l))

    limits=['-D', 'MAXSTRINGLEN=4096', '-D', 'MAXBACKTRACE=200',
            '-D', 'MAXMAPENTRIES=10240']

    stap_cmd.extend(limits)

    p = subprocess.Popen(stap_cmd)
    p.wait()


if __name__ == '__main__':
    main()
